# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(666, 604)
        self.horizontalSlider_train = QtWidgets.QSlider(Form)
        self.horizontalSlider_train.setGeometry(QtCore.QRect(130, 100, 471, 16))
        self.horizontalSlider_train.setMaximum(100)
        self.horizontalSlider_train.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_train.setObjectName("horizontalSlider_train")
        self.horizontalSlider_validation = QtWidgets.QSlider(Form)
        self.horizontalSlider_validation.setGeometry(QtCore.QRect(130, 150, 471, 16))
        self.horizontalSlider_validation.setMaximum(100)
        self.horizontalSlider_validation.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_validation.setObjectName("horizontalSlider_validation")
        self.horizontalSlider_test = QtWidgets.QSlider(Form)
        self.horizontalSlider_test.setGeometry(QtCore.QRect(130, 200, 471, 16))
        self.horizontalSlider_test.setMaximum(100)
        self.horizontalSlider_test.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_test.setObjectName("horizontalSlider_test")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 100, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 71, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 200, 41, 17))
        self.label_3.setObjectName("label_3")
        self.label_train = QtWidgets.QLabel(Form)
        self.label_train.setGeometry(QtCore.QRect(620, 90, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_train.setFont(font)
        self.label_train.setText("")
        self.label_train.setObjectName("label_train")
        self.label_validation = QtWidgets.QLabel(Form)
        self.label_validation.setGeometry(QtCore.QRect(620, 140, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_validation.setFont(font)
        self.label_validation.setText("")
        self.label_validation.setObjectName("label_validation")
        self.label_test = QtWidgets.QLabel(Form)
        self.label_test.setGeometry(QtCore.QRect(620, 190, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_test.setFont(font)
        self.label_test.setText("")
        self.label_test.setObjectName("label_test")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(490, 490, 81, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(170, 30, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(245, 121, 0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(60, 320, 551, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(245, 121, 0);")
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(-60, 270, 741, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalSlider_size = QtWidgets.QSlider(Form)
        self.horizontalSlider_size.setGeometry(QtCore.QRect(100, 410, 471, 20))
        self.horizontalSlider_size.setMinimum(2)
        self.horizontalSlider_size.setMaximum(50)
        self.horizontalSlider_size.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_size.setObjectName("horizontalSlider_size")
        self.label_increase = QtWidgets.QLabel(Form)
        self.label_increase.setGeometry(QtCore.QRect(60, 410, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_increase.setFont(font)
        self.label_increase.setObjectName("label_increase")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(60, 490, 161, 17))
        self.label_10.setObjectName("label_10")
        self.label_total = QtWidgets.QLabel(Form)
        self.label_total.setGeometry(QtCore.QRect(240, 490, 67, 17))
        self.label_total.setStyleSheet("color: rgb(245, 121, 0);")
        self.label_total.setText("")
        self.label_total.setObjectName("label_total")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(150, 240, 381, 17))
        self.label_4.setStyleSheet("color: rgb(52, 101, 164);")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        self.horizontalSlider_train.valueChanged['int'].connect(self.label_train.setNum) # type: ignore
        self.horizontalSlider_validation.valueChanged['int'].connect(self.label_validation.setNum) # type: ignore
        self.horizontalSlider_test.valueChanged['int'].connect(self.label_test.setNum) # type: ignore
        self.horizontalSlider_size.valueChanged['int'].connect(self.label_increase.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Train"))
        self.label_2.setText(_translate("Form", "Validation"))
        self.label_3.setText(_translate("Form", "Test"))
        self.pushButton.setText(_translate("Form", "OK"))
        self.label_7.setText(_translate("Form", "How do you want to split the dataset?"))
        self.label_8.setText(_translate("Form", "By what amount would you like to increase the dataset size?"))
        self.label_increase.setText(_translate("Form", "2"))
        self.label_10.setText(_translate("Form", "Total number of image:"))
        self.label_4.setText(_translate("Form", "(Follow this order for arranging: Test - Validation - Train)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
