# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page6.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(672, 236)
        self.pushButton_output_path = QtWidgets.QPushButton(Form)
        self.pushButton_output_path.setGeometry(QtCore.QRect(110, 30, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_output_path.setFont(font)
        self.pushButton_output_path.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.pushButton_output_path.setObjectName("pushButton_output_path")
        self.label_output_path = QtWidgets.QLabel(Form)
        self.label_output_path.setGeometry(QtCore.QRect(50, 90, 571, 20))
        self.label_output_path.setStyleSheet("color: rgb(52, 101, 164);")
        self.label_output_path.setText("")
        self.label_output_path.setAlignment(QtCore.Qt.AlignCenter)
        self.label_output_path.setObjectName("label_output_path")
        self.pushButton_prepare = QtWidgets.QPushButton(Form)
        self.pushButton_prepare.setGeometry(QtCore.QRect(250, 130, 161, 41))
        self.pushButton_prepare.setStyleSheet("background-color: rgb(115, 210, 22);")
        self.pushButton_prepare.setObjectName("pushButton_prepare")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(190, 190, 281, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Get Outputs"))
        self.pushButton_output_path.setText(_translate("Form", "Choose a Path to Create Output Folder "))
        self.pushButton_prepare.setText(_translate("Form", "Prepare the Dataset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
