# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'augmentation_steps.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_add_augmentation(object):
    def setupUi(self, add_augmentation):
        add_augmentation.setObjectName("add_augmentation")
        add_augmentation.resize(404, 498)
        self.listWidget_aug = QtWidgets.QListWidget(add_augmentation)
        self.listWidget_aug.setGeometry(QtCore.QRect(80, 180, 261, 241))
        self.listWidget_aug.setObjectName("listWidget_aug")
        self.pushButton_addaug = QtWidgets.QPushButton(add_augmentation)
        self.pushButton_addaug.setGeometry(QtCore.QRect(80, 20, 261, 61))
        self.pushButton_addaug.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_addaug.setObjectName("pushButton_addaug")
        self.pushButton_removeaug = QtWidgets.QPushButton(add_augmentation)
        self.pushButton_removeaug.setGeometry(QtCore.QRect(80, 100, 261, 61))
        self.pushButton_removeaug.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.pushButton_removeaug.setObjectName("pushButton_removeaug")
        self.pushButton_next = QtWidgets.QPushButton(add_augmentation)
        self.pushButton_next.setGeometry(QtCore.QRect(120, 444, 181, 31))
        self.pushButton_next.setObjectName("pushButton_next")

        self.retranslateUi(add_augmentation)
        QtCore.QMetaObject.connectSlotsByName(add_augmentation)

    def retranslateUi(self, add_augmentation):
        _translate = QtCore.QCoreApplication.translate
        add_augmentation.setWindowTitle(_translate("add_augmentation", "Select Augmentation Methods"))
        self.pushButton_addaug.setText(_translate("add_augmentation", "Add Augmentation Step"))
        self.pushButton_removeaug.setText(_translate("add_augmentation", "Remove Selected Step"))
        self.pushButton_next.setText(_translate("add_augmentation", "Go To Next Step"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_augmentation = QtWidgets.QWidget()
    ui = Ui_add_augmentation()
    ui.setupUi(add_augmentation)
    add_augmentation.show()
    sys.exit(app.exec_())
