# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(672, 317)
        self.pushButton_dataset = QtWidgets.QPushButton(Form)
        self.pushButton_dataset.setGeometry(QtCore.QRect(210, 140, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_dataset.setFont(font)
        self.pushButton_dataset.setObjectName("pushButton_dataset")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(190, 40, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(21)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: rgb(245, 121, 0);")
        self.label.setObjectName("label")
        self.label_dataset = QtWidgets.QLabel(Form)
        self.label_dataset.setGeometry(QtCore.QRect(50, 200, 571, 20))
        self.label_dataset.setStyleSheet("color: rgb(52, 101, 164);")
        self.label_dataset.setText("")
        self.label_dataset.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dataset.setObjectName("label_dataset")
        self.pushButton_check = QtWidgets.QPushButton(Form)
        self.pushButton_check.setGeometry(QtCore.QRect(260, 240, 131, 41))
        self.pushButton_check.setObjectName("pushButton_check")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Data Augmentation App"))
        self.pushButton_dataset.setText(_translate("Form", "Specify the Dataset Path"))
        self.label.setText(_translate("Form", "Data Augmentation App"))
        self.pushButton_check.setText(_translate("Form", "Check Dataset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
