# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'brightness.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormBrightness(object):
    def setupUi(self, FormBrightness):
        FormBrightness.setObjectName("FormBrightness")
        FormBrightness.resize(633, 531)
        self.horizontalSlider_brightness = QtWidgets.QSlider(FormBrightness)
        self.horizontalSlider_brightness.setGeometry(QtCore.QRect(160, 380, 331, 16))
        self.horizontalSlider_brightness.setMaximum(100)
        self.horizontalSlider_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_brightness.setObjectName("horizontalSlider_brightness")
        self.label = QtWidgets.QLabel(FormBrightness)
        self.label.setGeometry(QtCore.QRect(70, 380, 81, 17))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(FormBrightness)
        self.pushButton.setGeometry(QtCore.QRect(280, 440, 71, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(FormBrightness)
        self.label_3.setGeometry(QtCore.QRect(520, 380, 31, 17))
        self.label_3.setObjectName("label_3")
        self.label_img_lighten = QtWidgets.QLabel(FormBrightness)
        self.label_img_lighten.setGeometry(QtCore.QRect(50, 30, 261, 271))
        self.label_img_lighten.setText("")
        self.label_img_lighten.setPixmap(QtGui.QPixmap("aug_methods/img.png"))
        self.label_img_lighten.setObjectName("label_img_lighten")
        self.label_img_darken = QtWidgets.QLabel(FormBrightness)
        self.label_img_darken.setGeometry(QtCore.QRect(330, 30, 261, 271))
        self.label_img_darken.setText("")
        self.label_img_darken.setPixmap(QtGui.QPixmap("aug_methods/img.png"))
        self.label_img_darken.setObjectName("label_img_darken")
        self.checkBox_lighten = QtWidgets.QCheckBox(FormBrightness)
        self.checkBox_lighten.setGeometry(QtCore.QRect(130, 310, 92, 23))
        self.checkBox_lighten.setObjectName("checkBox_lighten")
        self.checkBox_darken = QtWidgets.QCheckBox(FormBrightness)
        self.checkBox_darken.setGeometry(QtCore.QRect(420, 310, 92, 23))
        self.checkBox_darken.setObjectName("checkBox_darken")

        self.retranslateUi(FormBrightness)
        self.horizontalSlider_brightness.valueChanged['int'].connect(self.label_3.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FormBrightness)

    def retranslateUi(self, FormBrightness):
        _translate = QtCore.QCoreApplication.translate
        FormBrightness.setWindowTitle(_translate("FormBrightness", "Brightness"))
        self.label.setText(_translate("FormBrightness", "Brightness"))
        self.pushButton.setText(_translate("FormBrightness", "OK"))
        self.label_3.setText(_translate("FormBrightness", "0"))
        self.checkBox_lighten.setText(_translate("FormBrightness", "Lighten"))
        self.checkBox_darken.setText(_translate("FormBrightness", "Darken"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormBrightness = QtWidgets.QWidget()
    ui = Ui_FormBrightness()
    ui.setupUi(FormBrightness)
    FormBrightness.show()
    sys.exit(app.exec_())
