# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contrast.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormContrast(object):
    def setupUi(self, FormContrast):
        FormContrast.setObjectName("FormContrast")
        FormContrast.resize(633, 497)
        self.horizontalSlider_contrast = QtWidgets.QSlider(FormContrast)
        self.horizontalSlider_contrast.setGeometry(QtCore.QRect(160, 340, 331, 16))
        self.horizontalSlider_contrast.setMaximum(100)
        self.horizontalSlider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_contrast.setObjectName("horizontalSlider_contrast")
        self.label = QtWidgets.QLabel(FormContrast)
        self.label.setGeometry(QtCore.QRect(70, 340, 81, 17))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(FormContrast)
        self.pushButton.setGeometry(QtCore.QRect(280, 400, 71, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(FormContrast)
        self.label_3.setGeometry(QtCore.QRect(520, 340, 31, 17))
        self.label_3.setObjectName("label_3")
        self.label_img_dec = QtWidgets.QLabel(FormContrast)
        self.label_img_dec.setGeometry(QtCore.QRect(50, 40, 261, 271))
        self.label_img_dec.setText("")
        self.label_img_dec.setPixmap(QtGui.QPixmap("aug_methods/img.png"))
        self.label_img_dec.setObjectName("label_img_dec")
        self.label_img_inc = QtWidgets.QLabel(FormContrast)
        self.label_img_inc.setGeometry(QtCore.QRect(330, 40, 261, 271))
        self.label_img_inc.setText("")
        self.label_img_inc.setPixmap(QtGui.QPixmap("aug_methods/img.png"))
        self.label_img_inc.setObjectName("label_img_inc")

        self.retranslateUi(FormContrast)
        self.horizontalSlider_contrast.valueChanged['int'].connect(self.label_3.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FormContrast)

    def retranslateUi(self, FormContrast):
        _translate = QtCore.QCoreApplication.translate
        FormContrast.setWindowTitle(_translate("FormContrast", "Contrast"))
        self.label.setText(_translate("FormContrast", "Contrast"))
        self.pushButton.setText(_translate("FormContrast", "OK"))
        self.label_3.setText(_translate("FormContrast", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormContrast = QtWidgets.QWidget()
    ui = Ui_FormContrast()
    ui.setupUi(FormContrast)
    FormContrast.show()
    sys.exit(app.exec_())
