# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exposure.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormExposure(object):
    def setupUi(self, FormExposure):
        FormExposure.setObjectName("FormExposure")
        FormExposure.resize(412, 466)
        self.label = QtWidgets.QLabel(FormExposure)
        self.label.setGeometry(QtCore.QRect(30, 320, 71, 17))
        self.label.setObjectName("label")
        self.horizontalSlider_exposure = QtWidgets.QSlider(FormExposure)
        self.horizontalSlider_exposure.setGeometry(QtCore.QRect(110, 320, 231, 20))
        self.horizontalSlider_exposure.setMaximum(100)
        self.horizontalSlider_exposure.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_exposure.setObjectName("horizontalSlider_exposure")
        self.label_3 = QtWidgets.QLabel(FormExposure)
        self.label_3.setGeometry(QtCore.QRect(360, 320, 31, 17))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(FormExposure)
        self.pushButton.setGeometry(QtCore.QRect(170, 380, 71, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_img = QtWidgets.QLabel(FormExposure)
        self.label_img.setGeometry(QtCore.QRect(80, 20, 261, 271))
        self.label_img.setText("")
        self.label_img.setPixmap(QtGui.QPixmap("aug_methods/img.png"))
        self.label_img.setObjectName("label_img")

        self.retranslateUi(FormExposure)
        self.horizontalSlider_exposure.valueChanged['int'].connect(self.label_3.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FormExposure)

    def retranslateUi(self, FormExposure):
        _translate = QtCore.QCoreApplication.translate
        FormExposure.setWindowTitle(_translate("FormExposure", "Exposure"))
        self.label.setText(_translate("FormExposure", "Exposure"))
        self.label_3.setText(_translate("FormExposure", "0"))
        self.pushButton.setText(_translate("FormExposure", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormExposure = QtWidgets.QWidget()
    ui = Ui_FormExposure()
    ui.setupUi(FormExposure)
    FormExposure.show()
    sys.exit(app.exec_())
