# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grayscale.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormGrayscale(object):
    def setupUi(self, FormGrayscale):
        FormGrayscale.setObjectName("FormGrayscale")
        FormGrayscale.resize(399, 450)
        self.pushButton = QtWidgets.QPushButton(FormGrayscale)
        self.pushButton.setGeometry(QtCore.QRect(150, 380, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_img = QtWidgets.QLabel(FormGrayscale)
        self.label_img.setGeometry(QtCore.QRect(70, 30, 261, 271))
        self.label_img.setText("")
        self.label_img.setPixmap(QtGui.QPixmap("aug_methods/img.png"))
        self.label_img.setObjectName("label_img")
        self.checkBox = QtWidgets.QCheckBox(FormGrayscale)
        self.checkBox.setGeometry(QtCore.QRect(150, 330, 92, 23))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(FormGrayscale)
        QtCore.QMetaObject.connectSlotsByName(FormGrayscale)

    def retranslateUi(self, FormGrayscale):
        _translate = QtCore.QCoreApplication.translate
        FormGrayscale.setWindowTitle(_translate("FormGrayscale", "Grayscale"))
        self.pushButton.setText(_translate("FormGrayscale", "OK"))
        self.checkBox.setText(_translate("FormGrayscale", "Grayscale"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormGrayscale = QtWidgets.QWidget()
    ui = Ui_FormGrayscale()
    ui.setupUi(FormGrayscale)
    FormGrayscale.show()
    sys.exit(app.exec_())
