# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rotate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormRotate(object):
    def setupUi(self, FormRotate):
        FormRotate.setObjectName("FormRotate")
        FormRotate.resize(874, 427)
        self.checkBox_clockwise = QtWidgets.QCheckBox(FormRotate)
        self.checkBox_clockwise.setGeometry(QtCore.QRect(120, 370, 92, 23))
        self.checkBox_clockwise.setObjectName("checkBox_clockwise")
        self.pushButton = QtWidgets.QPushButton(FormRotate)
        self.pushButton.setGeometry(QtCore.QRect(390, 30, 81, 51))
        self.pushButton.setObjectName("pushButton")
        self.checkBox_counter_clockwise = QtWidgets.QCheckBox(FormRotate)
        self.checkBox_counter_clockwise.setGeometry(QtCore.QRect(360, 370, 151, 23))
        self.checkBox_counter_clockwise.setObjectName("checkBox_counter_clockwise")
        self.checkBox_upside_down = QtWidgets.QCheckBox(FormRotate)
        self.checkBox_upside_down.setGeometry(QtCore.QRect(650, 370, 111, 23))
        self.checkBox_upside_down.setObjectName("checkBox_upside_down")
        self.label_img_clockwise = QtWidgets.QLabel(FormRotate)
        self.label_img_clockwise.setGeometry(QtCore.QRect(40, 90, 261, 271))
        self.label_img_clockwise.setText("")
        self.label_img_clockwise.setPixmap(QtGui.QPixmap("img.png"))
        self.label_img_clockwise.setObjectName("label_img_clockwise")
        self.label_img_counter_clockwise = QtWidgets.QLabel(FormRotate)
        self.label_img_counter_clockwise.setGeometry(QtCore.QRect(310, 90, 261, 271))
        self.label_img_counter_clockwise.setText("")
        self.label_img_counter_clockwise.setPixmap(QtGui.QPixmap("img.png"))
        self.label_img_counter_clockwise.setObjectName("label_img_counter_clockwise")
        self.label_img_upside_down = QtWidgets.QLabel(FormRotate)
        self.label_img_upside_down.setGeometry(QtCore.QRect(580, 90, 261, 271))
        self.label_img_upside_down.setText("")
        self.label_img_upside_down.setPixmap(QtGui.QPixmap("img.png"))
        self.label_img_upside_down.setObjectName("label_img_upside_down")

        self.retranslateUi(FormRotate)
        QtCore.QMetaObject.connectSlotsByName(FormRotate)

    def retranslateUi(self, FormRotate):
        _translate = QtCore.QCoreApplication.translate
        FormRotate.setWindowTitle(_translate("FormRotate", "Rotate"))
        self.checkBox_clockwise.setText(_translate("FormRotate", "Clockwise"))
        self.pushButton.setText(_translate("FormRotate", "OK"))
        self.checkBox_counter_clockwise.setText(_translate("FormRotate", "Counter-Clockwise"))
        self.checkBox_upside_down.setText(_translate("FormRotate", "Upside Down"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormRotate = QtWidgets.QWidget()
    ui = Ui_FormRotate()
    ui.setupUi(FormRotate)
    FormRotate.show()
    sys.exit(app.exec_())
