# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sensitive_rotate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormSensitiveRotation(object):
    def setupUi(self, FormSensitiveRotation):
        FormSensitiveRotation.setObjectName("FormSensitiveRotation")
        FormSensitiveRotation.resize(651, 472)
        self.horizontalSlider = QtWidgets.QSlider(FormSensitiveRotation)
        self.horizontalSlider.setGeometry(QtCore.QRect(180, 350, 311, 20))
        self.horizontalSlider.setMaximum(45)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.pushButton = QtWidgets.QPushButton(FormSensitiveRotation)
        self.pushButton.setGeometry(QtCore.QRect(280, 400, 89, 41))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(FormSensitiveRotation)
        self.label.setGeometry(QtCore.QRect(520, 350, 31, 17))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(FormSensitiveRotation)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 21, 17))
        self.label_3.setObjectName("label_3")
        self.label_img_dec = QtWidgets.QLabel(FormSensitiveRotation)
        self.label_img_dec.setGeometry(QtCore.QRect(50, 40, 261, 271))
        self.label_img_dec.setText("")
        self.label_img_dec.setPixmap(QtGui.QPixmap("img.png"))
        self.label_img_dec.setObjectName("label_img_dec")
        self.label_4 = QtWidgets.QLabel(FormSensitiveRotation)
        self.label_4.setGeometry(QtCore.QRect(460, 20, 21, 17))
        self.label_4.setObjectName("label_4")
        self.label_img_inc = QtWidgets.QLabel(FormSensitiveRotation)
        self.label_img_inc.setGeometry(QtCore.QRect(340, 40, 261, 271))
        self.label_img_inc.setText("")
        self.label_img_inc.setPixmap(QtGui.QPixmap("img.png"))
        self.label_img_inc.setObjectName("label_img_inc")
        self.label_2 = QtWidgets.QLabel(FormSensitiveRotation)
        self.label_2.setGeometry(QtCore.QRect(100, 350, 67, 17))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(FormSensitiveRotation)
        self.horizontalSlider.valueChanged['int'].connect(self.label.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FormSensitiveRotation)

    def retranslateUi(self, FormSensitiveRotation):
        _translate = QtCore.QCoreApplication.translate
        FormSensitiveRotation.setWindowTitle(_translate("FormSensitiveRotation", "Sensitive Rotation"))
        self.pushButton.setText(_translate("FormSensitiveRotation", "OK"))
        self.label.setText(_translate("FormSensitiveRotation", "0"))
        self.label_3.setText(_translate("FormSensitiveRotation", "-"))
        self.label_4.setText(_translate("FormSensitiveRotation", "+"))
        self.label_2.setText(_translate("FormSensitiveRotation", "Rotation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormSensitiveRotation = QtWidgets.QWidget()
    ui = Ui_FormSensitiveRotation()
    ui.setupUi(FormSensitiveRotation)
    FormSensitiveRotation.show()
    sys.exit(app.exec_())
