# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shear.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormShear(object):
    def setupUi(self, FormShear):
        FormShear.setObjectName("FormShear")
        FormShear.resize(1144, 549)
        self.label = QtWidgets.QLabel(FormShear)
        self.label.setGeometry(QtCore.QRect(370, 410, 81, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(FormShear)
        self.label_2.setGeometry(QtCore.QRect(370, 460, 67, 17))
        self.label_2.setObjectName("label_2")
        self.horizontalSlider_horizontal = QtWidgets.QSlider(FormShear)
        self.horizontalSlider_horizontal.setGeometry(QtCore.QRect(480, 410, 411, 16))
        self.horizontalSlider_horizontal.setMaximum(45)
        self.horizontalSlider_horizontal.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_horizontal.setObjectName("horizontalSlider_horizontal")
        self.horizontalSlider_vertical = QtWidgets.QSlider(FormShear)
        self.horizontalSlider_vertical.setGeometry(QtCore.QRect(480, 460, 401, 16))
        self.horizontalSlider_vertical.setMaximum(45)
        self.horizontalSlider_vertical.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_vertical.setObjectName("horizontalSlider_vertical")
        self.label_3 = QtWidgets.QLabel(FormShear)
        self.label_3.setGeometry(QtCore.QRect(920, 410, 31, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(FormShear)
        self.label_4.setGeometry(QtCore.QRect(920, 460, 31, 17))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(FormShear)
        self.pushButton.setGeometry(QtCore.QRect(190, 420, 71, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_img_area1 = QtWidgets.QLabel(FormShear)
        self.label_img_area1.setGeometry(QtCore.QRect(30, 40, 261, 271))
        self.label_img_area1.setText("")
        self.label_img_area1.setPixmap(QtGui.QPixmap("img.png"))
        self.label_img_area1.setObjectName("label_img_area1")
        self.label_img_area2 = QtWidgets.QLabel(FormShear)
        self.label_img_area2.setGeometry(QtCore.QRect(310, 40, 261, 271))
        self.label_img_area2.setText("")
        self.label_img_area2.setPixmap(QtGui.QPixmap("img.png"))
        self.label_img_area2.setObjectName("label_img_area2")
        self.label_img_area3 = QtWidgets.QLabel(FormShear)
        self.label_img_area3.setGeometry(QtCore.QRect(580, 40, 261, 271))
        self.label_img_area3.setText("")
        self.label_img_area3.setPixmap(QtGui.QPixmap("img.png"))
        self.label_img_area3.setObjectName("label_img_area3")
        self.label_img_area4 = QtWidgets.QLabel(FormShear)
        self.label_img_area4.setGeometry(QtCore.QRect(860, 40, 261, 271))
        self.label_img_area4.setText("")
        self.label_img_area4.setPixmap(QtGui.QPixmap("img.png"))
        self.label_img_area4.setObjectName("label_img_area4")
        self.label_area1 = QtWidgets.QLabel(FormShear)
        self.label_area1.setGeometry(QtCore.QRect(120, 320, 61, 17))
        self.label_area1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_area1.setObjectName("label_area1")
        self.label_area2 = QtWidgets.QLabel(FormShear)
        self.label_area2.setGeometry(QtCore.QRect(410, 320, 61, 17))
        self.label_area2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_area2.setObjectName("label_area2")
        self.label_area3 = QtWidgets.QLabel(FormShear)
        self.label_area3.setGeometry(QtCore.QRect(690, 320, 61, 17))
        self.label_area3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_area3.setObjectName("label_area3")
        self.label_area4 = QtWidgets.QLabel(FormShear)
        self.label_area4.setGeometry(QtCore.QRect(960, 320, 61, 17))
        self.label_area4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_area4.setObjectName("label_area4")

        self.retranslateUi(FormShear)
        self.horizontalSlider_horizontal.valueChanged['int'].connect(self.label_3.setNum) # type: ignore
        self.horizontalSlider_vertical.valueChanged['int'].connect(self.label_4.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FormShear)

    def retranslateUi(self, FormShear):
        _translate = QtCore.QCoreApplication.translate
        FormShear.setWindowTitle(_translate("FormShear", "Shear"))
        self.label.setText(_translate("FormShear", "Horizontal"))
        self.label_2.setText(_translate("FormShear", "Vertical"))
        self.label_3.setText(_translate("FormShear", "0"))
        self.label_4.setText(_translate("FormShear", "0"))
        self.pushButton.setText(_translate("FormShear", "OK"))
        self.label_area1.setText(_translate("FormShear", "0,0"))
        self.label_area2.setText(_translate("FormShear", "0,0"))
        self.label_area3.setText(_translate("FormShear", "0,0"))
        self.label_area4.setText(_translate("FormShear", "0,0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormShear = QtWidgets.QWidget()
    ui = Ui_FormShear()
    ui.setupUi(FormShear)
    FormShear.show()
    sys.exit(app.exec_())
